package autogenscripts

import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.util.cio.*
import io.ktor.utils.io.*
import kotlinx.coroutines.runBlocking
import java.io.File
import java.util.zip.ZipFile
import kotlin.system.exitProcess

const val ROOT_PATH = "app/src/commonMain/kotlin/"
const val ROOT_PACKAGE_PATH = "it/vercruysse/lemmyapi/"
const val ROOT_PACKAGE = "it.vercruysse.lemmyapi."
const val ENUMS_PACKAGE = "enums."

val filesThatShouldNotBeAdded = setOf("SuccessResponse", "OpenGraphData", "AllLemmyErrors", "NodeInfo", "NodeInfoServices", "NodeInfoSoftware", "NodeInfoUsage", "NodeInfoUsers")
val propsThatShouldBeInt = setOf("my_vote")

// ============================================================
// Enum Replacement Configuration
// ============================================================

// Field names whose String type should be replaced with a specific enum, regardless of which file they appear in.
// File-specific overrides take priority (see fileFieldEnumOverrides below).
val globalFieldEnums = mapOf(
    "listing_type" to "ListingType",
    "registration_mode" to "RegistrationMode",
    "subscribed" to "SubscribedType",
    "feature_type" to "PostFeatureType",
    "post_listing_mode" to "PostListingMode",
    "default_comment_sort_type" to "CommentSortType",
    "sort_type" to "SortType",
    "visibility" to "CommunityVisibility",
    "follow_state" to "CommunityFollowerState",
    "post_upvotes" to "FederationMode",
    "post_downvotes" to "FederationMode",
    "comment_upvotes" to "FederationMode",
    "comment_downvotes" to "FederationMode",
    "show_downvotes" to "VoteShow",
    "image_mode" to "ImageMode",
    // Defaults for ambiguous fields overridden per file below
    "type_" to "ListingType",
    "sort" to "SortType",
)

// Per-file overrides: fileName (without extension) → (fieldName → enum class).
// These take priority over globalFieldEnums for the given file.
val fileFieldEnumOverrides = mapOf(
    "GetComments"               to mapOf("sort" to "CommentSortType"),
    "GetPersonMentions"         to mapOf("sort" to "CommentSortType"),
    "GetReplies"                to mapOf("sort" to "CommentSortType"),
    "AdminListUsers"            to mapOf("sort" to "LocalUserSortType"),
    "ListMultiCommunities"      to mapOf("sort" to "MultiCommunitySortType", "type_" to "MultiCommunityListingType"),
    "ListPersonContent"         to mapOf("type_" to "PersonContentType"),
    "ListPersonSaved"           to mapOf("type_" to "PersonContentType"),
    "ListPersonLiked"           to mapOf("type_" to "PersonContentType"),
    "ListNotifications"         to mapOf("type_" to "NotificationDataType"),
    "ListReports"               to mapOf("type_" to "ReportType", "sort" to "ReportSortType"),
    "Search"                    to mapOf("type_" to "SearchType"),
    "SearchResponse"            to mapOf("type_" to "SearchType"),
    "GetModlog"                 to mapOf("type_" to "ModlogActionType"),
    "Notification"              to mapOf("kind" to "NotificationType"),
    "Modlog"                    to mapOf("kind" to "ModlogKind"),
    "GetFederatedInstances"     to mapOf("kind" to "GetFederatedInstancesKind"),
    "CommunityActions"          to mapOf("notifications" to "CommunityNotificationsMode"),
    "PostActions"               to mapOf("notifications" to "PostNotificationsMode"),
    "EditCommunityNotifications" to mapOf("mode" to "CommunityNotificationsMode"),
    "EditPostNotifications"     to mapOf("mode" to "PostNotificationsMode"),
    "ListPersons"              to mapOf("sort" to "PersonSortType"),
)

// ============================================================
// Sealed Interface Configuration
// ============================================================

// Sealed interfaces that are not generated by dukat but must exist in the datatypes package.
// Maps the interface name to its @JsonClassDiscriminator field, and whether it needs @Serializable.
data class SealedInterface(val discriminator: String, val serializable: Boolean = false)

// TODO: don't know yet if serializable required but also it breaks the generated code
val sealedInterfaces = mapOf(
    "PostOrCommentOrPrivateMessage" to SealedInterface("type_"),
    "ResolveObjectView"            to SealedInterface("type_"),
    "ReportCombinedView"            to SealedInterface("type_"),
    "NotificationData"              to SealedInterface("type_", serializable = false),
    "PostCommentCombinedView"       to SealedInterface("type_"),
)

// Which data classes implement which sealed interfaces and what @SerialName they carry.
data class SealedImpl(val serialName: String, val interfaces: List<String>)

val sealedImplementations = mapOf(
    "Comment"                to SealedImpl("comment",          listOf("PostOrCommentOrPrivateMessage")),
    "Post"                   to SealedImpl("post",             listOf("PostOrCommentOrPrivateMessage")),
    "PrivateMessage"         to SealedImpl("private_message",  listOf("PostOrCommentOrPrivateMessage")),
    "CommentView"            to SealedImpl("comment",          listOf("ResolveObjectView", "NotificationData", "PostCommentCombinedView")),
    "PostView"               to SealedImpl("post",             listOf("ResolveObjectView", "PostCommentCombinedView")),
    "CommunityView"          to SealedImpl("community",        listOf("ResolveObjectView")),
    "PersonView"             to SealedImpl("person",           listOf("ResolveObjectView")),
    "MultiCommunityView"     to SealedImpl("multi_community",  listOf("ResolveObjectView")),
    "CommentReportView"      to SealedImpl("comment",          listOf("ReportCombinedView")),
    "PostReportView"         to SealedImpl("post",             listOf("ReportCombinedView")),
    "CommunityReportView"    to SealedImpl("community",        listOf("ReportCombinedView")),
    "PrivateMessageReportView" to SealedImpl("private_message", listOf("ReportCombinedView")),
    "PrivateMessageView"     to SealedImpl("private_message",  listOf("NotificationData")),
    "ModlogView"             to SealedImpl("mod_action",       listOf("NotificationData")),
)

// ============================================================
// Helpers
// ============================================================

fun getTypesPath(
    version: String,
    temp: Boolean = true,
) = "$ROOT_PATH$ROOT_PACKAGE_PATH$version/datatypes" + if (temp) "/temp" else ""

fun getDownloadLink(tag: String) = "https://github.com/LemmyNet/lemmy-js-client/archive/refs/tags/$tag.zip"

/** Replaces `fieldName: String` with `fieldName: EnumClass` on a single line, adding the import if matched. */
fun String.replaceFieldEnum(
    fieldName: String,
    enumClass: String,
    imports: MutableSet<String>,
    rootPackage: String,
): String {
    val pattern = "$fieldName: String"
    if (!contains(pattern)) return this
    imports.add("import $rootPackage${ENUMS_PACKAGE}$enumClass")
    return replace(pattern, "$fieldName: $enumClass")
}

/**
 * Resolves `dynamic /* ... */` union types (produced by dukat for TypeScript union types)
 * back to the appropriate sealed interface type.
 */
fun resolveDynamicType(line: String): String {
    if ("dynamic" !in line) return line

    val sealedType = when {
        // Post (but not PostView) signals PostOrCommentOrPrivateMessage
        Regex("""\bPost\b(?!View)""").containsMatchIn(line) -> "PostOrCommentOrPrivateMessage"
        // ModlogView only appears in NotificationData, not ResolveObjectView
        "ModlogView" in line -> "NotificationData"
        // CommunityView only appears in ResolveObjectView
        "CommunityView" in line -> "ResolveObjectView"
        else -> return line
    }

    val isOptional = "= null" in line

    return line
        .replace(Regex("""List<dynamic /\*.*?\*/>"""), "List<$sealedType>")
        .replace(Regex("""dynamic /\*.*?\*/"""), "$sealedType${if (isOptional) "?" else ""}")
}

/** Applies all field→enum replacements to a single line. File-specific overrides take priority. */
fun applyEnumReplacements(line: String, fileName: String, imports: MutableSet<String>, rootPackage: String): String {
    val fileOverrides = fileFieldEnumOverrides[fileName] ?: emptyMap()
    val effectiveReplacements = globalFieldEnums + fileOverrides

    return effectiveReplacements.entries.fold(line) { acc, (fieldName, enumClass) ->
        acc.replaceFieldEnum(fieldName, enumClass, imports, rootPackage)
    }
}

/** Transforms a single line from dukat-output syntax to Kotlin data class syntax. */
fun processLine(line: String, fileName: String, imports: MutableSet<String>, rootPackage: String): String {
    var k = line
        .replace("interface ", "internal data class ")
        .replace("typealias ", "internal typealias ")
        .replace(" {", "(")
        .replace("}", ")")

    if (k.contains("?") && !k.contains("=")) k += " = null"
    if (k.contains(":")) k += ","

    k = k.replace(Regex("""\bvar\b"""), "val")
         .replace(Regex("""\bArray\b"""), "List")

    k = if (propsThatShouldBeInt.any { k.contains(it) }) {
        k.replace(Regex("""\bNumber\b"""), "Int")
    } else {
        k.replace(Regex("""\bNumber\b"""), "Long")
    }

    if ("my_vote" in k) {
        k = k.replace(Regex("""\bmy_vote: Int\? = null\b"""), "my_vote: Int = 0")
    }

    k = resolveDynamicType(k)
    k = applyEnumReplacements(k, fileName, imports, rootPackage)

    return k
}

/**
 * Adds @SerialName annotation and sealed interface implementations to a data class body,
 * if the type is configured in sealedImplementations.
 */
fun addSealedInterfaceImpl(content: String, fileName: String, imports: MutableSet<String>): String {
    val impl = sealedImplementations[fileName] ?: return content

    imports.add("import kotlinx.serialization.SerialName")
    val interfaceList = impl.interfaces.joinToString(", ")

    val withSerialName = content.replace(
        "internal data class $fileName(",
        "@SerialName(\"${impl.serialName}\")\ninternal data class $fileName(",
    )
    // Replace the last `)` (closing of the data class) with `) : InterfaceList`
    val lastParen = withSerialName.lastIndexOf(')')
    return withSerialName.substring(0, lastParen) + ") : $interfaceList" + withSerialName.substring(lastParen + 1)
}

/** Generates a sealed interface .kt file for each entry in sealedInterfaces. */
fun writeSealedInterfaces(datatypesDir: File, packageName: String) {
    for ((name, info) in sealedInterfaces) {
        val serializableImport = if (info.serializable) "\nimport kotlinx.serialization.Serializable" else ""
        val serializableAnnotation = if (info.serializable) "\n@Serializable" else ""

        File(datatypesDir, "$name.kt").writeText(
            """
            package $packageName

            import kotlinx.serialization.ExperimentalSerializationApi$serializableImport
            import kotlinx.serialization.json.JsonClassDiscriminator

            @OptIn(ExperimentalSerializationApi::class)$serializableAnnotation
            @JsonClassDiscriminator("${info.discriminator}")
            internal sealed interface $name
            """.trimIndent() + "\n"
        )
    }
}

/** Processes a single dukat-generated .d.kt file into a clean Kotlin datatype file. */
fun processDukatFile(typeFile: File, fileName: String, packageName: String, rootPackage: String) {
    val originalContent = typeFile.readText()
    val isTypealias = originalContent.contains("typealias")

    val imports = mutableSetOf<String>()
    if (!isTypealias) imports.add("import kotlinx.serialization.Serializable")

    val lines = originalContent
        .lines()
        .drop(16) // Remove dukat-generated header
        .filter { !it.contains("definedExternally") }
        .map { processLine(it, fileName, imports, rootPackage) }

    var body = lines.joinToString("\n")
    if (!isTypealias) body = addSealedInterfaceImpl(body, fileName, imports)

    val outputFile = File(typeFile.parentFile, "$fileName.kt")
    outputFile.writeText(buildString {
        appendLine("package $packageName")
        appendLine()
        imports.sorted().forEach { appendLine(it) }
        if (imports.isNotEmpty()) appendLine()
        if (!isTypealias) appendLine("@Serializable")
        append(body)
        if (!body.endsWith("\n")) appendLine()
    })

    typeFile.delete()
}

// ============================================================
// Main entry point
// ============================================================

// Requires that dukat is installed https://github.com/Kotlin/dukat
// Rewrites the TS types to Kotlin types
fun downloadTypes(
    version: String,
    subLocation: String,
) {
    val packageName = "$ROOT_PACKAGE${subLocation.replace("/", ".")}.datatypes"
    val tempDir = File("temp").also { it.mkdir() }
    val zipFile = File(tempDir, "lemmy-js.zip")

    runBlocking {
        client.get(getDownloadLink(version))
            .bodyAsChannel()
            .copyAndClose(zipFile.writeChannel())
    }

    // Extract .ts files to datatypes/temp/
    val tsDestDir = File(getTypesPath(subLocation)).also { it.mkdirs() }
    tsDestDir.listFiles()?.forEach { it.delete() }

    ZipFile(zipFile).use { zip ->
        val tsPath = "lemmy-js-client-$version/src/types/"
        for (entry in zip.entries()) {
            if (!entry.name.startsWith(tsPath) || entry.isDirectory) continue
            val name = entry.name.substring(tsPath.length)
            val nameOnly = name.substringBefore(".")
            if (nameOnly in filesThatShouldNotBeAdded) continue
            File(tsDestDir, name).writeBytes(zip.getInputStream(entry).readAllBytes())
        }
    }
    println("TS files extracted")

    val datatypesDir = File(getTypesPath(subLocation, false))
    datatypesDir.listFiles()?.forEach { if (it.name != "temp") it.deleteRecursively() }

    // Run dukat: reads from temp/*.ts, writes .d.kt files to datatypesDir
    println("Starting Dukat process...")
    val proc = ProcessBuilder("bash", "-ic", "dukat temp/*.ts", "exit")
        .directory(datatypesDir)
        .start()
    println(String(proc.inputStream.readAllBytes()))

    // Process each dukat-generated .d.kt → clean .kt
    datatypesDir.listFiles()!!.forEach { typeFile ->
        when {
            typeFile.name.startsWith("lib") -> typeFile.delete()
            typeFile.isFile && typeFile.name.endsWith(".kt") -> {
                val fileName = typeFile.name.substringBefore(".")
                processDukatFile(typeFile, fileName, packageName, ROOT_PACKAGE)
            }
        }
    }

    writeSealedInterfaces(datatypesDir, packageName)

    tsDestDir.deleteRecursively()
    tempDir.deleteRecursively()
    println("Finished!")
}

fun main() {
    // Future version 1.0.0-beta.1
    downloadTypes("1.0.0-beta.1", "v1/x0/x0")
    exitProcess(0)
}
